### ISSUE TITLE
Article on libchip8 for PineTime Smart Watch

### ISSUE THREAD

**Issue by lupyuen** [YushiOMOTE/libchip8#1]
Hi: Thank you so much for creating the libchip8 emulator 😀

I have ported your emulator to run on PineTime Smart Watch as an exercise for free open-source IoT Education.

Here's the article...
 https://lupyuen.github.io/pinetime-rust-mynewt/articles/chip8
 
Thanks again 😀

Lup

**Comment by YushiOMOTE** [comment]
Hi, thank you for using libchip8 for writing such a great article 😄 

I've read your article. Especially pixel mapping part to show nice graphic is awesome.

Iibchip8 probably feels happy.

Thanks!

Yushi

**Comment by lupyuen** [comment]
Thanks again and I hope you'll continue creating awesome Rust libraries :-)
